# Generated by Django 4.2.4 on 2024-04-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Formulario',
        ),
    ]
