# Generated by Django 4.2.4 on 2024-04-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_rename_note_formulario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='title',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='formulario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='pergunta',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
