# Generated by Django 4.2.4 on 2024-04-16 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulario', '0003_rename_title_formulario_nome_formulario_ativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='pergunta',
            new_name='perguntas',
        ),
        migrations.AddField(
            model_name='formulario',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
