# Generated by Django 4.2.1 on 2024-04-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_formulario_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='author',
        ),
    ]
