# Generated by Django 4.2.4 on 2024-04-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_perguntas_remove_formulario_pergunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.formulario')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.perguntas')),
            ],
        ),
    ]
