# Generated by Django 4.2.1 on 2024-04-26 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_formulariopergunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervalos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.PositiveIntegerField()),
                ('enunciado_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.perguntas')),
            ],
        ),
    ]
